# Generated by Django 2.1.3 on 2018-11-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název')),
                ('related_law', models.CharField(max_length=255, verbose_name='Související zákon(y)')),
                ('base_description', models.TextField(verbose_name='Základní popis')),
                ('usecase_description', models.TextField(verbose_name='K čemu slouží')),
                ('claim_description', models.TextField(verbose_name='Kdo má nárok')),
                ('other_description', models.TextField(blank=True, verbose_name='Další informace')),
            ],
            options={
                'verbose_name': 'Dávka',
                'verbose_name_plural': 'Dávky',
            },
        ),
        migrations.CreateModel(
            name='BenefitAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulek')),
                ('file', models.FileField(upload_to='', verbose_name='Soubor')),
            ],
            options={
                'verbose_name': 'Příloha k popisu dávky',
                'verbose_name_plural': 'Přílohy k popisu dávky',
            },
        ),
        migrations.CreateModel(
            name='LifeCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
                ('description', models.TextField(verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Źivotní situace',
                'verbose_name_plural': 'Životní situace',
            },
        ),
        migrations.CreateModel(
            name='StateOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název')),
                ('short_name', models.CharField(help_text='např. OSSZ', max_length=50, verbose_name='Zkratka názvu')),
            ],
            options={
                'verbose_name': 'Úřad',
                'verbose_name_plural': 'Úřady',
            },
        ),
        migrations.AddField(
            model_name='benefit',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.LifeCondition'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='attachments',
            field=models.ManyToManyField(related_name='benefits', to='core.BenefitAttachment'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='responsible_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.StateOffice'),
        ),
    ]
