# Generated by Django 2.1.3 on 2018-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='benefits', to='core.BenefitAttachment'),
        ),
        migrations.AlterField(
            model_name='lifecondition',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
    ]
