# Generated by Django 2.1.3 on 2018-11-22 14:49

import bitfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181121_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ('condition', 'name'), 'verbose_name': 'Dávka', 'verbose_name_plural': 'Dávky'},
        ),
        migrations.AlterModelOptions(
            name='lifecondition',
            options={'ordering': ('title',), 'verbose_name': 'Źivotní situace', 'verbose_name_plural': 'Životní situace'},
        ),
        migrations.AddField(
            model_name='benefit',
            name='requirements',
            field=bitfield.models.BitField([('osobni-situace:svobodny-svobodna', 'Jaká je vaše osobní situace? : svobodný/svobodná'), ('osobni-situace:zenaty-vdana', 'Jaká je vaše osobní situace? : ženatý/vdaná'), ('osobni-situace:neformalni-vztah', 'Jaká je vaše osobní situace? : v neformálním vztahu'), ('osobni-situace:rozvedeny-rozvedena', 'Jaká je vaše osobní situace? : rozvedený/rozvedená'), ('osobni-situace:vdovec-vdova', 'Jaká je vaše osobní situace? : vdovec/vdova'), ('osobni-situace:student', 'Jaká je vaše osobní situace? : jsem student/studentka'), ('osobni-situace:nezamestnany', 'Jaká je vaše osobní situace? : jsem nezaměstnaný/nezaměstnaná'), ('osobni-situace:pece-o-ozp', 'Jaká je vaše osobní situace? : pečuji o osobu se zdravotním postižením'), ('osobni-situace:ozp', 'Jaká je vaše osobní situace? : jsem OZP'), ('osobni-situace:duchodce', 'Jaká je vaše osobní situace? : jsem důchodce'), ('rodina:ano', 'Čekáte rodinu? : ano'), ('rodina:ne', 'Čekáte rodinu? : ne')], default=0, verbose_name='Požadavky na získání dávky'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefits', to='core.LifeCondition', verbose_name='Situace'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='responsible_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.StateOffice', verbose_name='Žádost se podává na'),
        ),
    ]
