# Generated by Django 2.1.3 on 2018-11-27 16:39

import bitfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181124_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenefitManager',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='usecase_description',
        ),
        migrations.AlterField(
            model_name='benefitrequirement',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.Benefit', verbose_name='Dávka'),
        ),
        migrations.AlterField(
            model_name='benefitrequirement',
            name='flags',
            field=bitfield.models.BitField([('bit_0', 'Jsem svobodný/rozvedený, samoživitel'), ('bit_1', 'Jsem svobodná/rozvedená samoživitelka'), ('bit_2', 'Jsme rodina'), ('bit_3', 'Čekám dítě'), ('bit_5', 'Mám dítě do 4 let'), ('bit_6', 'Mám dítě do 6 let'), ('bit_7', 'Mám dítě do 18 let'), ('bit_8', 'Máme doma studenta do 26 let'), ('bit_9', 'Jsem senior'), ('bit_10', 'Jsem vdova/vdovec'), ('bit_11', 'Situace osamělého dítěte'), ('bit_12', 'Situace ohroženého dítěte'), ('bit_13', 'Jsem pěstoun'), ('bit_14', 'Jsem nezaměstnaný'), ('bit_15', 'Chybí mi peníze na živobytí'), ('bit_16', 'Příjem mojí domácnosti je nižší než 2,7 násobek životního minima'), ('bit_17', 'Nemám prostředky na placení nájmu'), ('bit_18', 'Nemám prostředky na kauci na nájem'), ('bit_19', 'Jsem v obtížné životní situaci'), ('bit_20', 'Jsem nemocný'), ('bit_21', 'Jsem po úrazu'), ('bit_22', 'Mám zdravotní hendikep'), ('bit_23', 'Pečuji o blízkou osobu, která je nemocná'), ('bit_24', 'Pečuji o blízkou osobu, která je po úrazu'), ('bit_25', 'Pečuji o blízkou osobu, která je zdravotně znevýhodněná'), ('bit_26', 'V rodině došlo k úmrtí'), ('bit_4', 'Jsem čerstvý rodič')], default=0, help_text='Požadavky v rámci jednoho záznamu mají logický význam NEBO. Dohoromady jsou pak spojeny logickou podmínkou A ZÁROVEŇ.', verbose_name='Požadavky'),
        ),
    ]
