# Generated by Django 2.1.3 on 2018-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181127_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='context_description',
            field=models.TextField(blank=True, help_text='Počet udělených dávek apod.', verbose_name='Kontextové informace'),
        ),
    ]
