# Generated by Django 2.1.3 on 2018-11-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_benefit_context_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='related_law',
            field=models.TextField(verbose_name='Související zákon(y)'),
        ),
    ]
