# Generated by Django 2.1.3 on 2019-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190220_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='searchable',
            field=models.BooleanField(default=True, verbose_name='Lze vyhledat pomocí formuláře?'),
        ),
    ]
