# Generated by Django 2.1.3 on 2018-12-02 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, help_text='Oddělujte čárkou', max_length=150, verbose_name='Klíčová slova')),
                ('description', models.TextField(blank=True, verbose_name='Krátký popis')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage', verbose_name='Stránka')),
            ],
            options={
                'verbose_name': 'Metadata statické stránky',
                'verbose_name_plural': 'Metadata statických stránek',
            },
        ),
    ]
