# Generated by Django 2.1.3 on 2019-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190120_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpagemeta',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulek'),
        ),
    ]
